// flow-typed signature: 6fc3519f30f95223458feda95fd51862
// flow-typed version: <<STUB>>/chroma-js_v^1.2.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chroma-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chroma-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chroma-js/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/chroma.min' {
  declare module.exports: any;
}

declare module 'chroma-js/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chroma-js/chroma.js' {
  declare module.exports: $Exports<'chroma-js/chroma'>;
}
declare module 'chroma-js/chroma.min.js' {
  declare module.exports: $Exports<'chroma-js/chroma.min'>;
}
declare module 'chroma-js/Gruntfile.js' {
  declare module.exports: $Exports<'chroma-js/Gruntfile'>;
}
