// flow-typed signature: 64850c05eec2dca84e26e27abe03c5de
// flow-typed version: <<STUB>>/random-seed_v^0.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-seed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-seed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-seed/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'random-seed/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'random-seed/gulpfile' {
  declare module.exports: any;
}

declare module 'random-seed/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-seed/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'random-seed/coverage/lcov-report/prettify'>;
}
declare module 'random-seed/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'random-seed/coverage/lcov-report/sorter'>;
}
declare module 'random-seed/gulpfile.js' {
  declare module.exports: $Exports<'random-seed/gulpfile'>;
}
declare module 'random-seed/index' {
  declare module.exports: $Exports<'random-seed'>;
}
declare module 'random-seed/index.js' {
  declare module.exports: $Exports<'random-seed'>;
}
declare module 'random-seed/test.js' {
  declare module.exports: $Exports<'random-seed/test'>;
}
