// flow-typed signature: ab375ed45373d27267a103799bc86a97
// flow-typed version: <<STUB>>/react-vis_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vis/dist/animation' {
  declare module.exports: any;
}

declare module 'react-vis/dist/index' {
  declare module.exports: any;
}

declare module 'react-vis/dist/legends/continuous-color-legend' {
  declare module.exports: any;
}

declare module 'react-vis/dist/legends/continuous-size-legend' {
  declare module.exports: any;
}

declare module 'react-vis/dist/legends/discrete-color-legend-item' {
  declare module.exports: any;
}

declare module 'react-vis/dist/legends/discrete-color-legend' {
  declare module.exports: any;
}

declare module 'react-vis/dist/legends/searchable-discrete-color-legend' {
  declare module.exports: any;
}

declare module 'react-vis/dist/make-vis-flexible' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/axis-line' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/axis-ticks' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/axis-title' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/axis' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/x-axis' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/axis/y-axis' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/crosshair' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/grid-lines' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/hint' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/horizontal-grid-lines' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/abstract-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/area-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/bar-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/heatmap-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/horizontal-bar-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/horizontal-rect-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/line-mark-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/line-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/mark-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/rect-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/vertical-bar-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/series/vertical-rect-series' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/vertical-grid-lines' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/voronoi' {
  declare module.exports: any;
}

declare module 'react-vis/dist/plot/xy-plot' {
  declare module.exports: any;
}

declare module 'react-vis/dist/pure-render-component' {
  declare module.exports: any;
}

declare module 'react-vis/dist/radial-chart/index' {
  declare module.exports: any;
}

declare module 'react-vis/dist/sankey/index' {
  declare module.exports: any;
}

declare module 'react-vis/dist/theme' {
  declare module.exports: any;
}

declare module 'react-vis/dist/treemap/index' {
  declare module.exports: any;
}

declare module 'react-vis/dist/treemap/treemap-leaf' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/animation-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/axis-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/chart-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/data-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/react-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/scales-utils' {
  declare module.exports: any;
}

declare module 'react-vis/dist/utils/series-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vis/dist/animation.js' {
  declare module.exports: $Exports<'react-vis/dist/animation'>;
}
declare module 'react-vis/dist/index.js' {
  declare module.exports: $Exports<'react-vis/dist/index'>;
}
declare module 'react-vis/dist/legends/continuous-color-legend.js' {
  declare module.exports: $Exports<'react-vis/dist/legends/continuous-color-legend'>;
}
declare module 'react-vis/dist/legends/continuous-size-legend.js' {
  declare module.exports: $Exports<'react-vis/dist/legends/continuous-size-legend'>;
}
declare module 'react-vis/dist/legends/discrete-color-legend-item.js' {
  declare module.exports: $Exports<'react-vis/dist/legends/discrete-color-legend-item'>;
}
declare module 'react-vis/dist/legends/discrete-color-legend.js' {
  declare module.exports: $Exports<'react-vis/dist/legends/discrete-color-legend'>;
}
declare module 'react-vis/dist/legends/searchable-discrete-color-legend.js' {
  declare module.exports: $Exports<'react-vis/dist/legends/searchable-discrete-color-legend'>;
}
declare module 'react-vis/dist/make-vis-flexible.js' {
  declare module.exports: $Exports<'react-vis/dist/make-vis-flexible'>;
}
declare module 'react-vis/dist/plot/axis/axis-line.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/axis-line'>;
}
declare module 'react-vis/dist/plot/axis/axis-ticks.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/axis-ticks'>;
}
declare module 'react-vis/dist/plot/axis/axis-title.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/axis-title'>;
}
declare module 'react-vis/dist/plot/axis/axis.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/axis'>;
}
declare module 'react-vis/dist/plot/axis/x-axis.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/x-axis'>;
}
declare module 'react-vis/dist/plot/axis/y-axis.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/axis/y-axis'>;
}
declare module 'react-vis/dist/plot/crosshair.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/crosshair'>;
}
declare module 'react-vis/dist/plot/grid-lines.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/grid-lines'>;
}
declare module 'react-vis/dist/plot/hint.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/hint'>;
}
declare module 'react-vis/dist/plot/horizontal-grid-lines.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/horizontal-grid-lines'>;
}
declare module 'react-vis/dist/plot/series/abstract-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/abstract-series'>;
}
declare module 'react-vis/dist/plot/series/area-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/area-series'>;
}
declare module 'react-vis/dist/plot/series/bar-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/bar-series'>;
}
declare module 'react-vis/dist/plot/series/heatmap-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/heatmap-series'>;
}
declare module 'react-vis/dist/plot/series/horizontal-bar-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/horizontal-bar-series'>;
}
declare module 'react-vis/dist/plot/series/horizontal-rect-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/horizontal-rect-series'>;
}
declare module 'react-vis/dist/plot/series/line-mark-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/line-mark-series'>;
}
declare module 'react-vis/dist/plot/series/line-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/line-series'>;
}
declare module 'react-vis/dist/plot/series/mark-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/mark-series'>;
}
declare module 'react-vis/dist/plot/series/rect-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/rect-series'>;
}
declare module 'react-vis/dist/plot/series/vertical-bar-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/vertical-bar-series'>;
}
declare module 'react-vis/dist/plot/series/vertical-rect-series.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/series/vertical-rect-series'>;
}
declare module 'react-vis/dist/plot/vertical-grid-lines.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/vertical-grid-lines'>;
}
declare module 'react-vis/dist/plot/voronoi.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/voronoi'>;
}
declare module 'react-vis/dist/plot/xy-plot.js' {
  declare module.exports: $Exports<'react-vis/dist/plot/xy-plot'>;
}
declare module 'react-vis/dist/pure-render-component.js' {
  declare module.exports: $Exports<'react-vis/dist/pure-render-component'>;
}
declare module 'react-vis/dist/radial-chart/index.js' {
  declare module.exports: $Exports<'react-vis/dist/radial-chart/index'>;
}
declare module 'react-vis/dist/sankey/index.js' {
  declare module.exports: $Exports<'react-vis/dist/sankey/index'>;
}
declare module 'react-vis/dist/theme.js' {
  declare module.exports: $Exports<'react-vis/dist/theme'>;
}
declare module 'react-vis/dist/treemap/index.js' {
  declare module.exports: $Exports<'react-vis/dist/treemap/index'>;
}
declare module 'react-vis/dist/treemap/treemap-leaf.js' {
  declare module.exports: $Exports<'react-vis/dist/treemap/treemap-leaf'>;
}
declare module 'react-vis/dist/utils/animation-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/animation-utils'>;
}
declare module 'react-vis/dist/utils/axis-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/axis-utils'>;
}
declare module 'react-vis/dist/utils/chart-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/chart-utils'>;
}
declare module 'react-vis/dist/utils/data-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/data-utils'>;
}
declare module 'react-vis/dist/utils/react-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/react-utils'>;
}
declare module 'react-vis/dist/utils/scales-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/scales-utils'>;
}
declare module 'react-vis/dist/utils/series-utils.js' {
  declare module.exports: $Exports<'react-vis/dist/utils/series-utils'>;
}
