// flow-typed signature: 2b5f55823fdc60a1948d995649bab6df
// flow-typed version: <<STUB>>/react-d3-library_v^1.1.8/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-d3-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-d3-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-d3-library/dist/react-d3-library' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/charts/createAreaChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/charts/createBarChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/charts/createLineChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/charts/createPieChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/charts/createScatterPlot' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/AreaChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/BarChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/ChildComponent' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/Component' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/LineChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/PieChart' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/d3Components/ScatterPlot' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/index' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/createReactComponents' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/d3DataToJSX' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/applyChartData' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/applyData' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/applyTransitionData' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/applyZoomData' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/mountD3Functions' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/registerEventListeners' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/element-properties/registerOnListeners' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/extractData' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/getAttributes' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/getStyles' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/react-d3/passReactState' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/utils/applyD3ReactId' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/utils/parseHTMLTag' {
  declare module.exports: any;
}

declare module 'react-d3-library/lib/utils/toCamelCase' {
  declare module.exports: any;
}

declare module 'react-d3-library/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-d3-library/dist/react-d3-library.js' {
  declare module.exports: $Exports<'react-d3-library/dist/react-d3-library'>;
}
declare module 'react-d3-library/lib/charts/createAreaChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/charts/createAreaChart'>;
}
declare module 'react-d3-library/lib/charts/createBarChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/charts/createBarChart'>;
}
declare module 'react-d3-library/lib/charts/createLineChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/charts/createLineChart'>;
}
declare module 'react-d3-library/lib/charts/createPieChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/charts/createPieChart'>;
}
declare module 'react-d3-library/lib/charts/createScatterPlot.js' {
  declare module.exports: $Exports<'react-d3-library/lib/charts/createScatterPlot'>;
}
declare module 'react-d3-library/lib/d3Components/AreaChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/AreaChart'>;
}
declare module 'react-d3-library/lib/d3Components/BarChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/BarChart'>;
}
declare module 'react-d3-library/lib/d3Components/ChildComponent.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/ChildComponent'>;
}
declare module 'react-d3-library/lib/d3Components/Component.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/Component'>;
}
declare module 'react-d3-library/lib/d3Components/LineChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/LineChart'>;
}
declare module 'react-d3-library/lib/d3Components/PieChart.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/PieChart'>;
}
declare module 'react-d3-library/lib/d3Components/ScatterPlot.js' {
  declare module.exports: $Exports<'react-d3-library/lib/d3Components/ScatterPlot'>;
}
declare module 'react-d3-library/lib/index.js' {
  declare module.exports: $Exports<'react-d3-library/lib/index'>;
}
declare module 'react-d3-library/lib/react-d3/createReactComponents.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/createReactComponents'>;
}
declare module 'react-d3-library/lib/react-d3/d3DataToJSX.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/d3DataToJSX'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/applyChartData.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/applyChartData'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/applyData.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/applyData'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/applyTransitionData.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/applyTransitionData'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/applyZoomData.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/applyZoomData'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/mountD3Functions.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/mountD3Functions'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/registerEventListeners.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/registerEventListeners'>;
}
declare module 'react-d3-library/lib/react-d3/element-properties/registerOnListeners.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/element-properties/registerOnListeners'>;
}
declare module 'react-d3-library/lib/react-d3/extractData.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/extractData'>;
}
declare module 'react-d3-library/lib/react-d3/getAttributes.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/getAttributes'>;
}
declare module 'react-d3-library/lib/react-d3/getStyles.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/getStyles'>;
}
declare module 'react-d3-library/lib/react-d3/passReactState.js' {
  declare module.exports: $Exports<'react-d3-library/lib/react-d3/passReactState'>;
}
declare module 'react-d3-library/lib/utils/applyD3ReactId.js' {
  declare module.exports: $Exports<'react-d3-library/lib/utils/applyD3ReactId'>;
}
declare module 'react-d3-library/lib/utils/parseHTMLTag.js' {
  declare module.exports: $Exports<'react-d3-library/lib/utils/parseHTMLTag'>;
}
declare module 'react-d3-library/lib/utils/toCamelCase.js' {
  declare module.exports: $Exports<'react-d3-library/lib/utils/toCamelCase'>;
}
declare module 'react-d3-library/webpack.config.js' {
  declare module.exports: $Exports<'react-d3-library/webpack.config'>;
}
