// flow-typed signature: 31b933d201000cd401f0369356d49c8c
// flow-typed version: <<STUB>>/react-dimensions_v^1.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dimensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-dimensions/index' {
  declare module.exports: $Exports<'react-dimensions'>;
}
declare module 'react-dimensions/index.js' {
  declare module.exports: $Exports<'react-dimensions'>;
}
